services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  ia:
    build:
      context: ./services/ia
    container_name: ia
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  messenger-whatsapp:
    build:
      context: ./services/messenger-whatsapp
    container_name: messenger-whatsapp
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

networks:
  default:
    driver: bridge
