apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  OPENAI_API_KEY: "<base64-encoded-openai-api-key>"
  LANGSMITH_API_KEY: "<base64-encoded-langsmith-api-key>"
  GRAPH_API_TOKEN: "<base64-encoded-graph-api-token>"