apiVersion: v1
kind: Secret
metadata:
  name: messenger-whatsapp-tls-cert
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-private-key>
